openapi: 3.0.3
info:
  title: Chat API
  description: API for chat interactions and task management
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Development server

paths:
  /chat/chat:
    post:
      summary: Send a message to the AI assistant
      description: Process user message and return AI response with potential task operations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful response from the AI assistant
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /chat/conversations:
    get:
      summary: Get conversation history
      description: Retrieve a conversation's history
      parameters:
        - name: conversation_id
          in: query
          required: false
          schema:
            type: string
            format: uuid
          description: Specific conversation ID to retrieve
      responses:
        '200':
          description: Successfully retrieved conversation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationResponse'
        '400':
          description: Bad request - invalid conversation ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /tasks:
    get:
      summary: Get all tasks
      description: Retrieve all tasks for the authenticated user
      responses:
        '200':
          description: Successfully retrieved tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new task
      description: Create a new task for the authenticated user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Message content
          example: "Create a task to buy groceries"
        conversation_id:
          type: string
          format: uuid
          description: Conversation ID (creates new if not provided)
          example: "123e4567-e89b-12d3-a456-426614174000"

    ChatResponse:
      type: object
      required:
        - message
        - conversation_id
      properties:
        message:
          $ref: '#/components/schemas/Message'
        conversation_id:
          type: string
          description: ID of the conversation
          example: "123e4567-e89b-12d3-a456-426614174000"

    ConversationResponse:
      type: object
      required:
        - id
        - title
        - messages
        - updated_at
      properties:
        id:
          type: string
          description: Conversation ID
          example: "123e4567-e89b-12d3-a456-426614174000"
        title:
          type: string
          description: Conversation title
          example: "Grocery list"
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
        updated_at:
          type: string
          format: date-time
          description: Last updated timestamp

    Message:
      type: object
      required:
        - id
        - content
        - role
        - created_at
      properties:
        id:
          type: string
          format: uuid
          description: Message ID
          example: "123e4567-e89b-12d3-a456-426614174000"
        content:
          type: string
          description: Message content
          example: "Task 'buy groceries' created successfully"
        role:
          type: string
          enum: [user, assistant]
          description: Role of the message sender
        created_at:
          type: string
          format: date-time
          description: Creation timestamp

    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - is_completed
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Task ID
          example: "123e4567-e89b-12d3-a456-426614174000"
        user_id:
          type: string
          format: uuid
          description: User ID who owns the task
          example: "987e6543-e21c-32d1-b654-321456987000"
        title:
          type: string
          description: Task title
          example: "Buy groceries"
        description:
          type: string
          description: Task description
          example: "Milk, eggs, bread"
        is_completed:
          type: boolean
          description: Completion status
          example: false
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp

    CreateTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: Task title
          example: "Buy groceries"
        description:
          type: string
          description: Task description
          example: "Milk, eggs, bread"

    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message
          example: "Something went wrong"